### ISSUE TITLE
Flake - compile option

### ISSUE THREAD

**Issue by blaggacao** [nix-community/nixos-cli#1]
I wonder whether it's feasible, to avoid the `--flake` mistake of the past.

Let's face it: you either are sold (and use flakes everywhere [you can]) or you aren't and don't touch them [if you can].

So instead, would it be possible to simply have two compile options of `nixos`? One with and one without flake? -- and avoid unhandy flags.

**Comment by water-sucks** [comment]
That's fair, I like the idea.

I think that in terms of argument parsing, I'd want to still rely on the `NIXOS_CONFIG` variable for an implicit location of the flake, so we don't have to specify `--flake <FLAKEREF>` every time; would the argument for the flake ref be better as a positional argument, or is a `--ref <FLAKEREF>` flag better for that sort of thing?

**Comment by blaggacao** [comment]
> I'd want to still rely on the NIXOS_CONFIG variable for an implicit location of the flake

That's an excellent idea for the local case. :+1: 

> would the argument for the flake ref be better as a positional argument, or is a --ref <FLAKEREF> flag better for that sort of thing?

It depends. If we want to enable the HM folks to write a `nixos hm` plugin, then we need to start thinking about a flake-fragment schema that will be supported, e.g. `nixos hm apply my-env` translates internally to:
 `${NIXOS_CONFIG:``pwd``}#homeConfigurations.<system>.my-env`, while `nixos hm apply <TAB>` would resolve to the same.
 
 In the light of "not-only-NixOS" configurations (via extensions), maybe worth calling the environment variable `SYSTEM_CONFIG`, instead of `NIXOS_CONFIG`...

 Similarily, `nixos apply my-os` could resolve to `${SYSTEM_CONFIG:``pwd``}#nixosConfigurations.<system>.my-os`, etc.

**Comment by water-sucks** [comment]
I have an introductory PR that implements this, if you'd like to take a look and see if there's any problems with it.
