### ISSUE TITLE
Support `nix-output-manager` out of the box

### ISSUE THREAD

**Issue by doronbehar** [nix-community/nixos-cli#13]
Hello!

Very nice project :) It would be interesting if this tool, for it's `nixos-rebuild` equivalent, it'd support using [`nom`](https://github.com/maralorn/nix-output-monitor) if it is available.

Best.

**Comment by water-sucks** [comment]
Hi! Thanks for checking this out, and for the feature request.

A lot of people seem to want this, so I'll be down to implement support for this when I have some downtime.

I personally don't prefer using `nom`, but I presume using it by default, and adding an option in the config to disable `nom` usage is probably an OK way for going about this.

**Comment by water-sucks** [comment]
@doronbehar I've implemented basic support for the `nixos apply` command to use `nom` as an alternate builder, both as a CLI flag and as a configuration option in cbae0446f28ec91f6d48eb237b133b0414888581.

It falls back to using Nix to build if `nom` is not found, unless `--use-nom` is specified explicitly.
