### ISSUE TITLE
Build failure attribute 'mdDoc' missing

### ISSUE THREAD

**Issue by Luk45135** [nix-community/nixos-cli#48]
### What Happened?

I encountered this issue a while back, but didn't report it then.
Apparently it's missing mdDoc even though it's been removed from nixpkgs https://github.com/NixOS/nixpkgs/pull/303841
```
┏━ 1 Errors: 
 ⋮ 
┃        … while evaluating the attribute 'value'
┃          at /nix/store/22r7q7s9552gn1vpjigkbhfgcvhsrz68-source/lib/modules.nix:846:9:
┃           845|     in warnDeprecation opt //
┃           846|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
┃              |         ^
┃           847|         inherit (res.defsFinal') highestPrio;
┃ 
┃        … while evaluating the option `system.build.toplevel':
┃ 
┃        … while evaluating definitions from `/nix/store/22r7q7s9552gn1vpjigkbhfgcvhsrz68-source/nixos/modules/system/activation/top-level.nix':
┃ 
┃        … while evaluating the option `system.systemBuilderArgs':
┃ 
┃        … while evaluating definitions from `/nix/store/22r7q7s9552gn1vpjigkbhfgcvhsrz68-source/nixos/modules/system/activation/activatable-system.nix':
┃ 
┃        … while evaluating the option `system.activationScripts.etc.text':
┃ 
┃        … while evaluating definitions from `/nix/store/22r7q7s9552gn1vpjigkbhfgcvhsrz68-source/nixos/modules/system/etc/etc-activation.nix':
┃ 
┃        … while evaluating definitions from `/nix/store/22r7q7s9552gn1vpjigkbhfgcvhsrz68-source/nixos/modules/system/etc/etc.nix':
┃ 
┃        … while evaluating the option `environment.etc."nixos-cli/options-cache.json".source':
┃ 
┃        … while evaluating definitions from `/nix/store/22r7q7s9552gn1vpjigkbhfgcvhsrz68-source/nixos/modules/system/etc/etc.nix':
┃ 
┃        … while evaluating the option `environment.etc."nixos-cli/options-cache.json".text':
┃ 
┃        … while evaluating definitions from `/nix/store/f1gybp4q6kw3vq7iqgdnncncp6bs3ggp-source/flake.nix#nixosModules.nixos-cli':
┃ 
┃        (stack trace truncated; use '--show-trace' to show the full, detailed trace)
┃ 
┃        error: attribute 'mdDoc' missing
┃        at /nix/store/xdv56a1sma9x1a7sp1mvnkxlyfw1iz7j-source/modules/options.nix:128:19:
┃           127|     default = { };
┃           128|     description = lib.mdDoc ''
┃              |                   ^
┃           129|       Applies the provided attribute set into a Flatpak overrides file with the
┣━━━                                                             
┗━ ∑ ⚠ Exited with 1 errors reported by nix at 09:13:29 after 49s
```

### How To Reproduce

I'm using unstable and you can find my config for nixos-cli here: https://github.com/Luk45135/nixos-config/blob/main/system/services/nixos-cli.nix

### Expected Behavior

I expected to build nixos-cli without problems.

### Features

```shell
Can't run it as it's not building.
```

**Comment by water-sucks** [comment]
Ah I see. I did a bit of sleuthing, and found out that you are using an [older version of `nix-flatpak`](https://github.com/Luk45135/nixos-config/blob/fbd1a31a989f5e0434a7eaabaafc14c9aa519a5e/flake.nix#L21) that uses this removed `lib.mdDoc` function.

Are you able to use a newer version? [v0.5.2](https://github.com/gmodena/nix-flatpak/releases/tag/v0.5.2) seems to be the latest version as of now.

I'll need to add a failsafe for this sort of error, because it definitely is a bit annoying and another person has [ran into this before](https://github.com/water-sucks/nixos/issues/41) but that'll require me to make a custom function for parsing options that does have failsafes for poorly defined options, instead of just using `lib.optionAttrSetToDocList` like a lazy guy.

**Comment by Luk45135** [comment]
Oh, i saw that issue before when trying to search for what was going on, but my understanding was lacking. I did find it weird as to why flatpak was mentioned in the error even though the only thing i changed was enabling nixos-cli, but i didn't think far enough to connect the dots. After updating nix-flatpak to use the latest ref it works without problems now, thanks.
