### ISSUE TITLE
Nix import packages from external package sources

### ISSUE THREAD

**Issue by tauoverpi** [nix-community/nixos-cli#9]
A thing I felt odd when I used nix was the scattered package import tools that would parse cran, pypi, crates, and such compared to guix where all of those tools are maintained as part of the guix cli itself. Thus it would be nice if this tool would also handle package imports from external package repositories in a similar way.

https://guix.gnu.org/en/manual/en/html_node/Invoking-guix-import.html

**Comment by water-sucks** [comment]
Hi, thanks for the request!

I think it's a great idea, however I don't believe it is is within scope of NixOS tooling, but rather Nix tooling. Perhaps a similar `nix import` command would make sense as a Nix plugin, or upstreamed into the actual CLI, but it doesn't make sense to include here. Sorry!
